apiVersion: apps/v1
kind: Deployment
metadata:
  name: dataset-calculation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dataset-calculation
  template:
    metadata:
      labels:
        app: dataset-calculation
    spec:
      containers:
        - name: dataset-calculation
          image: your-docker-repo/dataset-calculation:latest
          ports:
            - containerPort: 8080