apiVersion: v1
kind: Service
metadata:
  name: dataset-calculation-service
spec:
  type: NodePort
  selector:
    app: dataset-calculation
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30001 # Optional