apiVersion: v1
kind: Service
metadata:
  name: dataset-calculation-service
spec:
  type: LoadBalancer
  selector:
    app: dataset-calculation
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080